# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "motoki-2023-09"
client_id = "d364e4610c640a7d79da7770d6001817"
application_url = "https://nevertheless-utc-plane-arabia.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nevertheless-utc-plane-arabia.trycloudflare.com/auth/callback",
  "https://nevertheless-utc-plane-arabia.trycloudflare.com/auth/shopify/callback",
  "https://nevertheless-utc-plane-arabia.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "motoki-development-store.myshopify.com"
